apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
spec:
  stripPrefix:
    prefixes:
      - /nginx-test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-test
  annotations:
    "traefik.ingress.kubernetes.io/router.middlewares": default-stripprefix@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /nginx-test
            pathType: Exact
            backend:
              service:
                name:  nginx-service
                port:
                  number: 80
